export const TYPES = {
  // Infrastructure
  UserRepository: Symbol.for('UserRepository'),
  AdminRepository: Symbol.for('AdminRepository'),
  DeveloperProfileRepository: Symbol.for('DeveloperProfileRepository'),
  CompanyProfileRepository: Symbol.for('CompanyProfileRepository'),
  CompanyTeamRepository: Symbol.for('CompanyTeamRepository'),
  ConversationRepository: Symbol.for('ConversationRepository'),
  MessageRepository: Symbol.for('MessageRepository'),
  PendingUserRepository: Symbol.for('PendingUserRepository'),
  OTPRepository: Symbol.for('OTPRepository'),
  RefreshTokenRepository: Symbol.for('RefreshTokenRepository'),
  HashService: Symbol.for('HashService'),
  TokenService: Symbol.for('TokenService'),
  AuthTokenService: Symbol.for('AuthTokenService'),
  GoogleAuthService: Symbol.for('GoogleAuthService'),
  EmailService: Symbol.for('EmailService'),
  FileService: Symbol.for('FileService'),
  PaymentService: Symbol.for('PaymentService'),
  CryptographicService: Symbol.for('CryptographicService'),
  OfferLetterRepository: Symbol.for('OfferLetterRepository'),

  // Auth module
  RegisterUserUseCase: Symbol.for('RegisterUserUseCase'),
  VerifyEmailUseCase: Symbol.for('VerifyEmailUseCase'),
  LoginUseCase: Symbol.for('LoginUseCase'),
  AdminLoginUseCase: Symbol.for('AdminLoginUseCase'),
  ResendOTPUseCase: Symbol.for('ResendOTPUseCase'),
  ForgotPasswordUseCase: Symbol.for('ForgotPasswordUseCase'),
  ResetPasswordUseCase: Symbol.for('ResetPasswordUseCase'),
  RefreshTokenUseCase: Symbol.for('RefreshTokenUseCase'),
  LogoutUseCase: Symbol.for('LogoutUseCase'),
  AuthController: Symbol.for('AuthController'),
  GoogleLoginUseCase: Symbol.for('GoogleLoginUseCase'),
  GoogleRegisterUseCase: Symbol.for('GoogleRegisterUseCase'),

  // Profile module
  CreateDeveloperProfileUseCase: Symbol.for('CreateDeveloperProfileUseCase'),
  GetDeveloperProfileUseCase: Symbol.for('GetDeveloperProfileUseCase'),
  CreateCompanyProfileUseCase: Symbol.for('CreateCompanyProfileUseCase'),
  GetCompanyProfileUseCase: Symbol.for('GetCompanyProfileUseCase'),
  UpdateDeveloperProfileUseCase: Symbol.for('UpdateDeveloperProfileUseCase'),
  UpdateCompanyProfileUseCase: Symbol.for('UpdateCompanyProfileUseCase'),
  ResubmitDocumentsUseCase: Symbol.for('ResubmitDocumentsUseCase'),
  InviteCompanyTeamMemberUseCase: Symbol.for('InviteCompanyTeamMemberUseCase'),
  ListCompanyTeamMembersUseCase: Symbol.for('ListCompanyTeamMembersUseCase'),
  ProfileController: Symbol.for('ProfileController'),

  // Payment module
  CreateCheckoutSessionUseCase: Symbol.for('CreateCheckoutSessionUseCase'),
  HandleStripeWebhookUseCase: Symbol.for('HandleStripeWebhookUseCase'),
  CompletePaymentUseCase: Symbol.for('CompletePaymentUseCase'),
  PaymentController: Symbol.for('PaymentController'),

  // Plan module
  PlanRepository: Symbol.for('PlanRepository'),
  PaymentTransactionRepository: Symbol.for('PaymentTransactionRepository'),
  CreatePlanUseCase: Symbol.for('CreatePlanUseCase'),
  UpdatePlanUseCase: Symbol.for('UpdatePlanUseCase'),
  DeletePlanUseCase: Symbol.for('DeletePlanUseCase'),
  ListPlansUseCase: Symbol.for('ListPlansUseCase'),
  GetPlanByIdUseCase: Symbol.for('GetPlanByIdUseCase'),
  PlanController: Symbol.for('PlanController'),

  // File module
  GenerateSignatureUseCase: Symbol.for('GenerateSignatureUseCase'),
  DeleteFileUseCase: Symbol.for('DeleteFileUseCase'),
  FileController: Symbol.for('FileController'),

  // Admin module
  BlockUserUseCase: Symbol.for('BlockUserUseCase'),
  UnblockUserUseCase: Symbol.for('UnblockUserUseCase'),
  ApproveCompanyUseCase: Symbol.for('ApproveCompanyUseCase'),
  RejectCompanyUseCase: Symbol.for('RejectCompanyUseCase'),
  ListCompaniesUseCase: Symbol.for('ListCompaniesUseCase'),
  ListDevelopersUseCase: Symbol.for('ListDevelopersUseCase'),
  AdminController: Symbol.for('AdminController'),

  // Job Field module
  JobFieldRepository: Symbol.for('JobFieldRepository'),
  CreateJobFieldUseCase: Symbol.for('CreateJobFieldUseCase'),
  GetJobFieldsUseCase: Symbol.for('GetJobFieldsUseCase'),
  UpdateJobFieldUseCase: Symbol.for('UpdateJobFieldUseCase'),
  DeleteJobFieldUseCase: Symbol.for('DeleteJobFieldUseCase'),
  JobFieldController: Symbol.for('JobFieldController'),

  // Job module
  JobRepository: Symbol.for('JobRepository'),
  CreateJobUseCase: Symbol.for('CreateJobUseCase'),
  ListJobsUseCase: Symbol.for('ListJobsUseCase'),
  DeleteJobUseCase: Symbol.for('DeleteJobUseCase'),
  CloseJobUseCase: Symbol.for('CloseJobUseCase'),
  OpenJobUseCase: Symbol.for('OpenJobUseCase'),
  UpdateJobUseCase: Symbol.for('UpdateJobUseCase'),
  GetJobUseCase: Symbol.for('GetJobUseCase'),
  JobController: Symbol.for('JobController'),

  // Application module
  ApplicationRepository: Symbol.for('ApplicationRepository'),
  CreateApplicationUseCase: Symbol.for('CreateApplicationUseCase'),
  ListApplicationsForCompanyUseCase: Symbol.for('ListApplicationsForCompanyUseCase'),
  GetApplicationDetailsUseCase: Symbol.for('GetApplicationDetailsUseCase'),
  ListApplicationsForDeveloperUseCase: Symbol.for('ListApplicationsForDeveloperUseCase'),
  WithdrawApplicationUseCase: Symbol.for('WithdrawApplicationUseCase'),
  GetApplicationMetricsUseCase: Symbol.for('GetApplicationMetricsUseCase'),
  ShortlistApplicationUseCase: Symbol.for('ShortlistApplicationUseCase'),
  RejectApplicationUseCase: Symbol.for('RejectApplicationUseCase'),
  ScheduleInterviewRoundUseCase: Symbol.for('ScheduleInterviewRoundUseCase'),
  UpdateInterviewResultUseCase: Symbol.for('UpdateInterviewResultUseCase'),
  GetInterviewsForInterviewerUseCase: Symbol.for('GetInterviewsForInterviewerUseCase'),
  VideoCallHelper: Symbol.for('VideoCallHelper'),
  GetOrCreateVideoCallUseCase: Symbol.for('GetOrCreateVideoCallUseCase'),
  StartVideoCallUseCase: Symbol.for('StartVideoCallUseCase'),
  EndVideoCallUseCase: Symbol.for('EndVideoCallUseCase'),
  ExtendOfferUseCase: Symbol.for('ExtendOfferUseCase'),
  AcceptOfferUseCase: Symbol.for('AcceptOfferUseCase'),
  DeclineOfferUseCase: Symbol.for('DeclineOfferUseCase'),
  CreateOfferLetterUseCase: Symbol.for('CreateOfferLetterUseCase'),
  GetOfferLetterUseCase: Symbol.for('GetOfferLetterUseCase'),
  RequestRescheduleUseCase: Symbol.for('RequestRescheduleUseCase'),
  RespondToRescheduleRequestUseCase: Symbol.for('RespondToRescheduleRequestUseCase'),
  RescheduleInterviewUseCase: Symbol.for('RescheduleInterviewUseCase'),
  ApplicationController: Symbol.for('ApplicationController'),
  InterviewController: Symbol.for('InterviewController'),
  OfferController: Symbol.for('OfferController'),

  // Public Job module
  PublicListJobsUseCase: Symbol.for('PublicListJobsUseCase'),
  PublicGetJobUseCase: Symbol.for('PublicGetJobUseCase'),
  PublicJobController: Symbol.for('PublicJobController'),

  // Chat module
  CheckCanMessageUseCase: Symbol.for('CheckCanMessageUseCase'),
  SendMessageUseCase: Symbol.for('SendMessageUseCase'),
  GetConversationsUseCase: Symbol.for('GetConversationsUseCase'),
  GetMessagesUseCase: Symbol.for('GetMessagesUseCase'),
  MarkMessageAsReadUseCase: Symbol.for('MarkMessageAsReadUseCase'),
  GetConversationUseCase: Symbol.for('GetConversationUseCase'),
  ValidateConversationParticipantUseCase: Symbol.for('ValidateConversationParticipantUseCase'),
  ChatController: Symbol.for('ChatController'),
};
